config/routes.rb
Rails.application.routes.draw do
  resources :post_labels
  get 'label/index'
  get 'label/show'
  get 'label/new'
  get 'label/edit'
  get 'label/create'
  get 'label/update'
  get 'label/destroy'
  resources :posts
  devise_for :users
  root to: "home#index"
  get 'home/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/post_label.rb
class PostLabel < ApplicationRecord
    belongs_to :label
    belongs_to :post
end

app/controllers/post_labels_controller.rb
class PostLabelsController < ApplicationController
  before_action :set_post_label, only: %i[ show edit update destroy ]

  # GET /post_labels or /post_labels.json
  def index
    @post_labels = PostLabel.all
  end

  # GET /post_labels/1 or /post_labels/1.json
  def show
  end

  # GET /post_labels/new
  def new
    @post_label = PostLabel.new
  end

  # GET /post_labels/1/edit
  def edit
  end

  # POST /post_labels or /post_labels.json
  def create
    @post_label = PostLabel.new(post_label_params)

    respond_to do |format|
      if @post_label.save
        format.html { redirect_to post_label_url(@post_label), notice: "Post label was successfully created." }
        format.json { render :show, status: :created, location: @post_label }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post_label.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_labels/1 or /post_labels/1.json
  def update
    respond_to do |format|
      if @post_label.update(post_label_params)
        format.html { redirect_to post_label_url(@post_label), notice: "Post label was successfully updated." }
        format.json { render :show, status: :ok, location: @post_label }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post_label.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_labels/1 or /post_labels/1.json
  def destroy
    @post_label.destroy

    respond_to do |format|
      format.html { redirect_to post_labels_url, notice: "Post label was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_label
      @post_label = PostLabel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_label_params
      params.fetch(:post_label, {})
    end
end

app/helpers/post_labels_helper.rb
module PostLabelsHelper
end

app/views/post_labels/_form.html.erb
<%= form_with(model: post_label) do |form| %>
  <% if post_label.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post_label.errors.count, "error") %> prohibited this post_label from being saved:</h2>

      <ul>
        <% post_label.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/post_labels/_post_label.html.erb
<div id="<%= dom_id post_label %>">
</div>

app/views/post_labels/edit.html.erb
<h1>Editing post label</h1>

<%= render "form", post_label: @post_label %>

<br>

<div>
  <%= link_to "Show this post label", @post_label %> |
  <%= link_to "Back to post labels", post_labels_path %>
</div>

app/views/post_labels/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Post labels</h1>

<div id="post_labels">
  <% @post_labels.each do |post_label| %>
    <%= render post_label %>
    <p>
      <%= link_to "Show this post label", post_label %>
    </p>
  <% end %>
</div>

<%= link_to "New post label", new_post_label_path %>

app/views/post_labels/new.html.erb
<h1>New post label</h1>

<%= render "form", post_label: @post_label %>

<br>

<div>
  <%= link_to "Back to post labels", post_labels_path %>
</div>

app/views/post_labels/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post_label %>

<div>
  <%= link_to "Edit this post label", edit_post_label_path(@post_label) %> |
  <%= link_to "Back to post labels", post_labels_path %>

  <%= button_to "Destroy this post label", @post_label, method: :delete %>
</div>