config/routes.rb
Rails.application.routes.draw do
  resources :post_labels
  get 'label/index'
  get 'label/show'
  get 'label/new'
  get 'label/edit'
  get 'label/create'
  get 'label/update'
  get 'label/destroy'
  resources :posts
  devise_for :users
  root to: "home#index"
  get 'home/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all.order("created_at DESC")
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_footer.html.erb
footer here

app/views/home/_header.html.erb
<!doctype html>
<html lang="en">
  <head>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js" defer></script>
    
    <title>Hello, world!</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%=link_to 'Medium', root_path, class:"navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%=link_to 'Home', root_path, class:"nav-link"%>
      </li>
      <li class="nav-item">
       <%=link_to 'About Us', home_about_path, class:"nav-link"%>
      </li>
      <li class="nav-item">
          <%=link_to 'Post', posts_path, class:"nav-link"%>
        </li>
      <%if user_signed_in?%>
        
        <li class="nav-item">
          <%=link_to 'Add Post', new_post_path, class:"nav-link"%>
        </li>
        <li class="nav-item ">
       <%= button_to 'Sign Out', destroy_user_session_path,method: :delete, class:"nav-link btn btn-dark btn-outline-dark"%>
      </li>
      <li class="nav-item">
       <%=link_to 'Edit profile', edit_user_registration_path, class:"nav-link"%>
      </li>
      <%else%>
      <li class="nav-item">
       <%=link_to 'Sign Up', new_user_registration_path, class:"nav-link"%>
      </li>
      <li class="nav-item">
       <%=link_to 'Sign in', new_user_session_path, class:"nav-link"%>
      </li>
      <%end%>
      
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
    <!-- Optional JavaScript -->
    <script src="js/jquery-3.3.1.min.js"></script>
    <script src="js/popper.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/chosen.jquery.min.js"></script>
    
    <script src="js/main.js"></script>
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
 <script>
   $(document).ready(function() {
    $('.js-example-basic-multiple').select2();
});
 </script>
  </body>
</html>

app/views/home/about.html.erb
<h1>About us</h1>

<p>This is the about us page content</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>